name: my-discord-bot
services:
- environment_slug: python
  github:
    branch: main
  run_command: python bot.py
  name: discord-bot-service
  environment_variables:
    - value: your-discord-bot-token
      scope: RUN_AND_BUILD_TIME
